### ISSUE TITLE
Error: expected primary-expression before `;` token

### ISSUE THREAD

**Issue by doronbehar** [pts/sam2p#13] opened 2017-09-08 17:10 UTC
https://github.com/pts/sam2p/blob/ac4dee3ddbcb7188b1936d6b47e0c42ff27b44aa/sam2p_main.cpp#L150-L152

I'm trying to build this package on archlinux from the aur and I get the error in the title. Any workaround?

**Comment by pts** [comment] 2017-09-09 16:58
Thank you for reporting this bug! Based on the error message it looks like the `bts2.tth` files is empty. As a workaround, you may want to remove this file and run `make` again. Unfortunately I'm not able to reproduce the problem, this works for me:

```
$ cd /tmp
$ git clone https://github.com/pts/sam2p
$ cd sam2p
$ make
```

If the commands above don't work for you, please copy-paste their full output.

**Comment by doronbehar** [comment] 2017-09-09 17:07
Hmm, I didn't get that error as well when I cloned clean the repository.
The aur package downloads the release tagged `v0.49.3`. Try to download
it, untar it and check.

**Comment by doronbehar** [comment] 2017-09-09 17:10
The error looks like that:
```
perl -pe0 bts.ttt l1g8z.pst l1ghz.pst l1gbz.pst l1g8l.pst l1ghl.pst l1gbl.pst >bts1.ttt                   
./ps_tiny --copy <bts1.ttt >bts2.ttt                 
perl -x hq.pl <bts2.ttt >bts2.tth                    
do "hq.pl" failed, '.' is no longer in @INC; did you mean do "./hq.pl"? at hq.pl line 2.                  
g++ --std=c++98 -s -O2 -DHAVE_CONFIG2_H   -fsigned-char -fno-rtti -fno-exceptions -ansi -pedantic -Wall -W -Wextra -c sam2p_main.cpp                                                                                
sam2p_main.cpp:152:1: error: expected primary-expression before ‘;’ token                                 
 ;
 ^
make: *** [Makedep:111: sam2p_main.o] Error 1 
```
It does seem like there is a problem with `bts2.tth`..

**Comment by pts** [comment] 2017-09-09 17:16
This error message is relevant:

```
do "hq.pl" failed, '.' is no longer in @INC; did you mean do "./hq.pl"? at hq.pl line 2.
```

In the Makefile, please change `hq.pl` to `./hq.pl`, delete the file `bts2.tth`, rerun `make`, and it should work. There are some other `perl -x` commands in the `Makefile`, you probably have to add `./` after all of them.

This problem was fixed on the master branch on GitHub. You may want to report this to your distribution maintainer, so that it will be fixed there as well.

**Closed as completed** 2017-09-09 17:17 UTC
